Traceback (most recent call last):
  File "C:\Users\Gustavo\PycharmProjects\Automating\Chapter10\tracebackUsage.py", line 4, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
